const INITIAL_SERVICES_DATA = [
    {
        "service": "ALBATROS SERVICE",
        "svc_code": "NWC MED",
        "terminal": "GWCT",
        "direction": "W",
        "tally": "PAN OCEAN",
        "lashing": "남양항운",
        "ports": [
            "CNTXG",
            "CNDLC",
            "KRKAN",
            "CNNGB",
            "CNXMN",
            "CNYTN",
            "SGSIN",
            "GBFXT",
            "DEBRV",
            "DKGBT",
            "DKGBT",
            "PLGDN",
            "LTKLJ",
            "DKGBT",
            "DKGBT",
            "BEANR",
            "GBFXT",
            "SGSIN",
            "CNSHA",
            "CNTXG"
        ]
    },
    {
        "service": "LION by P.A 여수 SWITCH DOC",
        "svc_code": "NWC MED PA - FE5",
        "terminal": "여수 ANCHOR",
        "direction": "W",
        "tally": "",
        "lashing": "",
        "ports": [
            "CNTAO",
            "KRYOS",
            "CNNGB",
            "CNSHA",
            "CNYTN",
            "SGSIN",
            "PTSIE",
            "FRLEH",
            "DEHAM",
            "NLRTM",
            "BEANR",
            "FRLEH",
            "GBLGP",
            "SGSIN",
            "CNTAO"
        ]
    },
    {
        "service": "SWAN by P.A",
        "svc_code": "NWC MED PA - FE6",
        "terminal": "BCT",
        "direction": "W",
        "tally": "해양공사",
        "lashing": "웨스턴 - VSA by P.A",
        "ports": [
            "KRPUS",
            "CNNGB",
            "CNSHA",
            "CNXMN",
            "CNYTN",
            "SGSIN",
            "GBFXT",
            "BEANR",
            "BEANR",
            "SEGOT",
            "DKAAR",
            "DEHAM",
            "DEBRV",
            "GBFXT",
            "CNSHK",
            "CNXMN",
            "KRPUS"
        ]
    },
    {
        "service": "GRIFFIN SERVICE by P.A",
        "svc_code": "NWC MED ONE - FP2W",
        "terminal": "HJNC",
        "direction": "W",
        "tally": "ONE - 신양 YML - 신양",
        "lashing": "ONE - KML YML - KML",
        "ports": [
            "KRPUS",
            "TWKHH",
            "CNSHA",
            "CNNGB",
            "CNYTN",
            "SGSIN",
            "GBSOU",
            "NLRTM",
            "SGSIN",
            "THLCH",
            "VNVUT",
            "VNHPH",
            "CNYTN",
            "KRPUS",
            "USTIW",
            "CAVAN",
            "KRPUS"
        ]
    },
    {
        "service": "SILK by P.A",
        "svc_code": "NWC MED ONE - FE4",
        "terminal": "HJNC",
        "direction": "W",
        "tally": "ONE - 해양",
        "lashing": "ONE - KML",
        "ports": [
            "CNSHA",
            "KRPUS",
            "NLRTM",
            "DEHAM",
            "FRLEH",
            "CNSHA"
        ]
    },
    {
        "service": "JADE SERVICE by P.A",
        "svc_code": "NWC MED PA - MD5",
        "terminal": "PNC",
        "direction": "W",
        "tally": "신양선박",
        "lashing": "웨스턴 - VSA by P.A",
        "ports": [
            "CNTAO",
            "KRPUS",
            "CNNGB",
            "CNSHA",
            "CNXMN",
            "CNYTN",
            "SGSIN",
            "ESVLC",
            "ESBCN",
            "FRFOS",
            "ITGIT",
            "SGSIN",
            "CNSHA",
            "CNTAO"
        ]
    },
    {
        "service": "TIGER SERVICE by P.A",
        "svc_code": "NWC MED PA - MD3",
        "terminal": "PNC",
        "direction": "W",
        "tally": "신양선박",
        "lashing": "웨스턴 - VSA by P.A",
        "ports": [
            "CNDLC",
            "CNTXG",
            "KRPUS",
            "CNNGB",
            "CNSHA",
            "CNSHK",
            "SGSIN",
            "ILASH",
            "TRCKZ",
            "TRCKZ",
            "TRYAR",
            "TRIST",
            "TRTEK",
            "TRCKZ",
            "TRCKZ",
            "TRMER",
            "EGDAM",
            "CIABJ",
            "TGLFW",
            "GHTEM",
            "HKHKG",
            "CNXMN",
            "CNDLC"
        ]
    },
    {
        "service": "PHOENIX",
        "svc_code": "NWC MED",
        "terminal": "PNC",
        "direction": "W",
        "tally": "미성 SNP",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "KRPUS",
            "CNNGB",
            "CNSHA",
            "CNSHK",
            "SGSIN",
            "ILHFA",
            "TRISK",
            "ITTRS",
            "SIKOP",
            "HRRJK",
            "TRALI",
            "SGSIN",
            "KRPUS"
        ]
    },
    {
        "service": "LYNX by P.A",
        "svc_code": "NWC MED PA - MD2W",
        "terminal": "DGT",
        "direction": "W",
        "tally": "ONE - 범아 HMM - 신양+해양(5:5) YML - 범아",
        "lashing": "ONE - KML HMM - 조영+KML YML - 동광",
        "ports": [
            "KRPUS",
            "CNSHA",
            "CNNGB",
            "TWKHH",
            "CNSHK",
            "SGSIN",
            "MAPTM",
            "ESVLC",
            "ESBCN",
            "ITGOA",
            "ITSPE",
            "FRFOS",
            "SGSIN",
            "THLCH",
            "VNVUT",
            "CNYTN",
            "KRPUS",
            "USLGB",
            "USOAK",
            "KRPUS"
        ]
    },
    {
        "service": "EMPIRE SERVICE E",
        "svc_code": "USA STRING ZIM - ZNS",
        "terminal": "BCT",
        "direction": "E",
        "tally": "해양공사",
        "lashing": "웨스턴 - VSA with ZIM",
        "ports": [
            "CNTAO",
            "CNSHA",
            "CNNGB",
            "KRPUS",
            "PAPTY",
            "PAPTY",
            "USNYC",
            "USBAL",
            "USJAX",
            "USMIA",
            "PAPTY",
            "PAPTY",
            "PAROD",
            "KRPUS",
            "CNTAO"
        ]
    },
    {
        "service": "EMPIRE SERVICE W",
        "svc_code": "USA STRING ZIM - ZNS",
        "terminal": "BCT",
        "direction": "W",
        "tally": "해양공사",
        "lashing": "웨스턴 - VSA with ZIM",
        "ports": [
            "PAROD",
            "KRPUS",
            "CNTAO",
            "CNSHA",
            "CNNGB",
            "KRPUS",
            "PAROD"
        ]
    },
    {
        "service": "AMBERJACK SERVICE E",
        "svc_code": "USA STRING ZIM - ZCP",
        "terminal": "BCT",
        "direction": "E",
        "tally": "ZIM - 미성 SNP",
        "lashing": "동신선박",
        "ports": [
            "CNYTN",
            "CNXMN",
            "CNNGB",
            "CNSHA",
            "KRPUS",
            "MXZLO",
            "PAPTY",
            "PAPTY",
            "JMKIN",
            "USSAV",
            "USCHS",
            "USORF",
            "JMKIN",
            "PAPTY"
        ]
    },
    {
        "service": "AMBERJACK SERVICE W",
        "svc_code": "USA STRING ZIM - ZCP",
        "terminal": "BCT",
        "direction": "W",
        "tally": "ZIM - 해양공사",
        "lashing": "동신선박",
        "ports": [
            "PAPTY",
            "KRPUS",
            "CNYTN",
            "CNXMN",
            "CNNGB",
            "CNSHA",
            "KRPUS"
        ]
    },
    {
        "service": "LONE STAR EXPRESS E",
        "svc_code": "USA STRING",
        "terminal": "BCT",
        "direction": "E",
        "tally": "미성 SNP",
        "lashing": "웨스턴 - VSA with ZIM",
        "ports": [
            "VNVUT",
            "CNYTN",
            "CNNGB",
            "CNSHA",
            "KRPUS",
            "PAPTY",
            "PAPTY",
            "USHOU",
            "USMOB",
            "USTPA",
            "USMIA",
            "BSFPO",
            "SGSIN",
            "VNVUT"
        ]
    },
    {
        "service": "ORIENT E",
        "svc_code": "USA STRING",
        "terminal": "PNC",
        "direction": "E",
        "tally": "신양선박",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "CNTAO",
            "CNNGB",
            "CNSHA",
            "KRPUS",
            "USLGB",
            "CNTAO"
        ]
    },
    {
        "service": "ORIENT W CHECKING",
        "svc_code": "USA STRING",
        "terminal": "PNIT",
        "direction": "W",
        "tally": "미성 SNP",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "USOAK",
            "KRPUS",
            "VNHPH",
            "CNNGB",
            "CNSHA",
            "KRPUS",
            "USLGB",
            "USOAK"
        ]
    },
    {
        "service": "CHINOOK A",
        "svc_code": "USA STRING",
        "terminal": "PNIT",
        "direction": "A - EAST",
        "tally": "해양공사",
        "lashing": "웨스턴 with ZIM",
        "ports": [
            "VNVUT",
            "CNYTN",
            "CNNGB",
            "CNSHA",
            "CNTAO",
            "KRPUS",
            "USSEA",
            "CAVAN",
            "CAPRR",
            "KRPUS",
            "VNVUT"
        ]
    },
    {
        "service": "CHINOOK R",
        "svc_code": "USA STRING",
        "terminal": "BCT",
        "direction": "R - WEST",
        "tally": "해양공사",
        "lashing": "웨스턴 with ZIM",
        "ports": [
            "CAPRR",
            "KRPUS",
            "VNVUT",
            "CNYTN",
            "CNNGB",
            "CNSHA",
            "CNTAO",
            "KRPUS",
            "USSEA"
        ]
    },
    {
        "service": "SENTOSA",
        "svc_code": "USA STRING",
        "terminal": "PNC",
        "direction": "W",
        "tally": "미성 SNP",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "USLGB",
            "USOAK",
            "KRPUS",
            "CNNGB",
            "SGSIN",
            "MYPKG",
            "THLCH",
            "VNVUT",
            "VNHPH",
            "CNYTN",
            "CNXMN",
            "USLGB",
            "USOAK"
        ]
    },
    {
        "service": "GRIFFIN SERVICE by P.A MSC NIL LOADING",
        "svc_code": "USA STRING ONE - FP2E",
        "terminal": "HJNC",
        "direction": "E",
        "tally": "ONE - 신양",
        "lashing": "ONE - KML",
        "ports": [
            "KRPUS",
            "TWKHH",
            "CNSHA",
            "CNNGB",
            "CNYTN",
            "SGSIN",
            "GBSOU",
            "NLRTM",
            "SGSIN",
            "THLCH",
            "VNVUT",
            "VNHPH",
            "CNYTN",
            "KRPUS",
            "USTIW",
            "CAVAN",
            "KRPUS"
        ]
    },
    {
        "service": "LYNX by P.A MSC NIL LOADING",
        "svc_code": "NWC MED PA - MD2E",
        "terminal": "HPNT",
        "direction": "E",
        "tally": "ONE - 해양 HMM - 신양+해양(5:5) YML - 범아",
        "lashing": "ONE - 고려기공 HMM - 조영+KML YML - 동광",
        "ports": [
            "KRPUS",
            "CNSHA",
            "CNNGB",
            "TWKHH",
            "CNSHK",
            "SGSIN",
            "MAPTM",
            "ESVLC",
            "ESBCN",
            "ITGOA",
            "ITSPE",
            "FRFOS",
            "SGSIN",
            "THLCH",
            "VNVUT",
            "CNYTN",
            "KRPUS",
            "USLGB",
            "USOAK",
            "KRPUS"
        ]
    },
    {
        "service": "IPANEMA SERVICE",
        "svc_code": "LATIN",
        "terminal": "PNIT",
        "direction": "A",
        "tally": "MSC - 신양 ONE - 국보 HLC - 범아",
        "lashing": "MSC - 웨스턴 ONE - KML(한국선박물류) HLC - 동신선박",
        "ports": [
            "KRPUS",
            "CNSHA",
            "CNNGB",
            "CNSHK",
            "HKHKG",
            "SGSIN",
            "BRSSZ",
            "BRPNG",
            "BRNVT",
            "UYMVD",
            "ARBUE",
            "BRRIG",
            "BRPNG",
            "BRNVT",
            "BRSSZ",
            "SGSIN",
            "HKHKG",
            "KRPUS"
        ]
    },
    {
        "service": "CARIOCA",
        "svc_code": "LATIN",
        "terminal": "PNIT",
        "direction": "A",
        "tally": "미성 SNP",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "CNTAO",
            "KRPUS",
            "CNSHA",
            "CNNGB",
            "CNSHK",
            "SGSIN",
            "INTRV",
            "BRRIO",
            "BRSSZ",
            "BRPNG",
            "BRIOA",
            "BRITJ",
            "ARBUE",
            "BRRIG",
            "BRITJ",
            "BRNVT",
            "BRPNG",
            "BRSSZ",
            "BRRIO",
            "NAWVB",
            "LKHBA",
            "HKHKG",
            "CNTAO"
        ]
    },
    {
        "service": "SANTANA",
        "svc_code": "IPAK",
        "terminal": "PNIT",
        "direction": "A",
        "tally": "신양선박",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "CNYTN",
            "CNNGB",
            "CNSHA",
            "CNTAO",
            "KRPUS",
            "PAPTY",
            "PAPTY",
            "PAONX",
            "PACTB",
            "DOCAU",
            "BRPEC",
            "BRSUA",
            "BRSSA",
            "BRSSZ",
            "LKHBA",
            "CNYTN"
        ]
    },
    {
        "service": "ANDES EXPRESS A",
        "svc_code": "LATIN ONE - AX2",
        "terminal": "PNIT",
        "direction": "A - EAST",
        "tally": "MSC - SNP ONE - 국보",
        "lashing": "MSC - 웨스턴 ONE - KML(한국선박물류)",
        "ports": [
            "CNSHA",
            "CNXMN",
            "CNSHK",
            "HKHKG",
            "CNNGB",
            "KRPUS",
            "MXZLO",
            "MXLZC",
            "PAROD",
            "COBUN",
            "PECLL",
            "CLSAI",
            "CLCNL",
            "CLLQN",
            "PECLL",
            "MXZLO",
            "MXZLO",
            "MXLZC",
            "JPYOK",
            "KRPUS"
        ]
    },
    {
        "service": "ANDES EXPRESS R",
        "svc_code": "LATIN ONE - AX2",
        "terminal": "PNIT",
        "direction": "R - WEST",
        "tally": "MSC - SNP ONE - 국보",
        "lashing": "MSC - 웨스턴 ONE - KML(한국선박물류)",
        "ports": [
            "MXZLO",
            "MXLZC",
            "JPYOK",
            "KRPUS",
            "CNSHA",
            "CNXMN",
            "CNSHK",
            "HKHKG",
            "CNNGB",
            "KRPUS"
        ]
    },
    {
        "service": "INCA",
        "svc_code": "LATIN ONE - AX1 HLC - AN1",
        "terminal": "PNIT",
        "direction": "E",
        "tally": "HLC - 신양 ONE - 해양 HMM - 신양",
        "lashing": "HLC - 코엠 ONE - 우진기업 HMM - 조영마린",
        "ports": [
            "HKHKG",
            "CNYTN",
            "TWKEL",
            "CNNGB",
            "CNSHA",
            "KRPUS",
            "MXZLO",
            "MXLZC",
            "PECLL",
            "CLIQQ",
            "CLPAG",
            "CLSVE",
            "CLVAP",
            "HKHKG"
        ]
    },
    {
        "service": "AZTEC E",
        "svc_code": "LATIN ONE - AX3 HMM - NW3",
        "terminal": "PNIT",
        "direction": "E",
        "tally": "MSC - SNP HLC - 범아 ONE - 범아 HMM - 해양",
        "lashing": "MSC - 웨스턴 HLC - 동신선박 ONE - 동양실업 HMM - KML(한국선박물류)",
        "ports": [
            "CNNGB",
            "CNSHA",
            "CNTAO",
            "KRPUS",
            "JPYOK",
            "MXESE",
            "MXZLO",
            "GTPRQ",
            "COBUN",
            "PECLL",
            "ECGYE",
            "COBUN",
            "PAROD",
            "MXLZC",
            "MXZLO",
            "JPYOK",
            "KRPUS",
            "CNNGB"
        ]
    },
    {
        "service": "AZTEC W",
        "svc_code": "LATIN ONE - AX3 HMM - NW3",
        "terminal": "PNIT",
        "direction": "W",
        "tally": "",
        "lashing": "MSC - 웨스턴 HLC - 동신선박 ONE - 동양실업 HMM - KML(한국선박물류)",
        "ports": [
            "MXZLO",
            "JPYOK",
            "KRPUS",
            "CNNGB",
            "CNSHA",
            "CNTAO",
            "KRPUS"
        ]
    },
    {
        "service": "MEXICAS",
        "svc_code": "LATIN",
        "terminal": "BCT",
        "direction": "A",
        "tally": "신양선박",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "CNNGB",
            "CNSHA",
            "CNTAO",
            "KRPUS",
            "MXLZC",
            "MXZLO",
            "MXESE",
            "CNNGB"
        ]
    },
    {
        "service": "ALPACA",
        "svc_code": "LATIN",
        "terminal": "PNIT",
        "direction": "A",
        "tally": "해양공사",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "CNNGB",
            "KRPUS",
            "PECLL",
            "CLARI",
            "CLIQQ",
            "CLSAI",
            "CLCNL",
            "PAROD",
            "CNNGB"
        ]
    },
    {
        "service": "PANDA",
        "svc_code": "OCEANIA",
        "terminal": "PNIT",
        "direction": "A",
        "tally": "MSC - 미성 SNP ZIM - 미성 SNP",
        "lashing": "MSC - 웨스턴 ZIM - 동신선박",
        "ports": [
            "KRPUS",
            "CNTAO",
            "CNSHA",
            "CNNGB",
            "CNNSA",
            "HKHKG",
            "CNYTN",
            "AUBNE",
            "AUSYD",
            "AUMEL",
            "AUBNE",
            "KRPUS"
        ]
    },
    {
        "service": "NEW FALCON SERVICE",
        "svc_code": "IPAK",
        "terminal": "PNIT",
        "direction": "A",
        "tally": "신양선박",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "CNTXG",
            "KRPUS",
            "CNTAO",
            "CNSHA",
            "CNNGB",
            "CNXMN",
            "CNNSA",
            "CNSHK",
            "SGSIN",
            "AEJEA",
            "AEAUH",
            "QAHMD",
            "IQUQR",
            "AEAUH",
            "CNNGB",
            "CNTXG"
        ]
    },
    {
        "service": "SHIKRA 여수 SWITCH DOC",
        "svc_code": "IPAK",
        "terminal": "여수 ANCHOR",
        "direction": "W",
        "tally": "",
        "lashing": "",
        "ports": [
            "CNDLC",
            "CNTXG",
            "KRYOS",
            "CNTAO",
            "CNSHA",
            "CNNGB",
            "CNNSA",
            "SGSIN",
            "INNSA",
            "INMUN",
            "PKKHI",
            "CNSHA",
            "CNDLC"
        ]
    },
    {
        "service": "AFRICA EXPRESS",
        "svc_code": "IPAK",
        "terminal": "BCT",
        "direction": "A",
        "tally": "신양선박",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "CNTXG",
            "KRPUS",
            "KRKAN",
            "CNNGB",
            "CNSHA",
            "CNNSA",
            "CNSHK",
            "VNVUT",
            "SGSIN",
            "INTRV",
            "GHTEM",
            "TGLFW",
            "CIABJ",
            "CMKBI",
            "INTRV",
            "VNVUT",
            "CNTAO",
            "CNTXG"
        ]
    },
    {
        "service": "AFRICA EXPRESS",
        "svc_code": "IPAK",
        "terminal": "GWCT",
        "direction": "A",
        "tally": "PAN OCEAN",
        "lashing": "남양항운",
        "ports": [
            "CNTXG",
            "KRPUS",
            "KRKAN",
            "CNNGB",
            "CNSHA",
            "CNNSA",
            "CNSHK",
            "VNVUT",
            "SGSIN",
            "INTRV",
            "GHTEM",
            "TGLFW",
            "CIABJ",
            "CMKBI",
            "INTRV",
            "VNVUT",
            "CNTAO",
            "CNTXG"
        ]
    },
    {
        "service": "PERTIWI",
        "svc_code": "INTRA ASIA",
        "terminal": "PNIT",
        "direction": "R",
        "tally": "신양선박",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "CNDLC",
            "CNTXG",
            "CNTAO",
            "CNSHK",
            "SGSIN",
            "IDJKT",
            "IDPNJ",
            "MYTPP",
            "SGSIN",
            "CNNSA",
            "HKHKG",
            "TWKHH",
            "KRPUS",
            "CNDLC"
        ]
    },
    {
        "service": "DOLPHIN",
        "svc_code": "INTRA ASIA",
        "terminal": "PNIT",
        "direction": "R",
        "tally": "미성 SNP",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "CNTAO",
            "CNDLC",
            "CNTXG",
            "CNSHK",
            "MYPKG",
            "SGSIN",
            "IDSRG",
            "IDSUB",
            "SGSIN",
            "VNHPH",
            "KRPUS",
            "CNTAO"
        ]
    },
    {
        "service": "ORIGAMI A",
        "svc_code": "IPAK",
        "terminal": "PNC",
        "direction": "A - SOUTH",
        "tally": "미성 SNP",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "JPTYO",
            "JPYOK",
            "JPYKK",
            "JPNGO",
            "KRPUS",
            "CNNGB",
            "SGSIN",
            "LKCMB",
            "KEMBA",
            "TZDAR",
            "SGSIN",
            "HKHKG",
            "KRPUS",
            "JPTYO"
        ]
    },
    {
        "service": "ORIGAMI R",
        "svc_code": "INTRA ASIA",
        "terminal": "PNC",
        "direction": "R - JAPAN",
        "tally": "미성 SNP",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "SGSIN",
            "HKHKG",
            "KRPUS",
            "JPTYO",
            "JPYOK",
            "JPYKK",
            "JPNGO",
            "KRPUS",
            "CNNGB",
            "SGSIN",
            "LKCMB",
            "KEMBA",
            "TZDAR",
            "SGSIN"
        ]
    },
    {
        "service": "KAGUYA",
        "svc_code": "INTRA ASIA",
        "terminal": "PNC",
        "direction": "R",
        "tally": "해양공사",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "JPUKB",
            "JPOSA",
            "KRPUS",
            "KRPUS",
            "JPUKB"
        ]
    },
    {
        "service": "KAGUYA",
        "svc_code": "INTRA ASIA",
        "terminal": "PNIT",
        "direction": "R",
        "tally": "해양공사",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "JPUKB",
            "JPOSA",
            "KRPUS",
            "KRPUS",
            "JPUKB"
        ]
    },
    {
        "service": "GOLDEN HORN",
        "svc_code": "INTRA ASIA",
        "terminal": "PNIT",
        "direction": "R",
        "tally": "미성 SNP",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "KRPUS",
            "RUVVO",
            "KRPUS"
        ]
    },
    {
        "service": "SUNRISE",
        "svc_code": "INTRA ASIA",
        "terminal": "PNIT",
        "direction": "A",
        "tally": "해양공사",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "KRPUS",
            "JPMOJ",
            "JPHKT",
            "KRPUS"
        ]
    },
    {
        "service": "SAMBAR",
        "svc_code": "INTRA ASIA",
        "terminal": "PNIT",
        "direction": "R",
        "tally": "해양공사",
        "lashing": "웨스턴 - MSC OWN",
        "ports": [
            "CNDLC",
            "KRINC",
            "CNTXG",
            "CNTAO",
            "CNDCB",
            "VNDNA",
            "THLCH",
            "SGSIN",
            "MYPEN",
            "MYPGU",
            "MYTPP",
            "SGSIN",
            "VNDNA",
            "KRPUS",
            "CNDLC"
        ]
    },
    {
        "service": "SAMBAR",
        "svc_code": "INTRA ASIA",
        "terminal": "ICT",
        "direction": "A",
        "tally": "신한선박",
        "lashing": "영화기업사",
        "ports": [
            "CNDLC",
            "KRINC",
            "CNTXG",
            "CNTAO",
            "CNDCB",
            "VNDNA",
            "THLCH",
            "SGSIN",
            "MYPEN",
            "MYPGU",
            "MYTPP",
            "SGSIN",
            "VNDNA",
            "KRPUS",
            "CNDLC"
        ]
    }
];